import type { Metadata } from "next"
import "@/src/app/styles/reset.css"
import "@/src/shared/ui/styles/vars.css"
import { Providers } from "@/src/app"
import styles from "./root-layout.module.css"
import clsx from "clsx"
import { philosopher } from "../fonts/philosopher"

// initServerSideMocks()

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
}

export function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode
}>) {
   return (
      <html lang="en">
         <Providers>
            <body className={clsx(styles.app, philosopher.className)}>
               {children}
               <div id="modal"></div>
            </body>
         </Providers>
      </html>
   )
}
