import type { Metadata } from "next"
import "@/src/app/styles/fonts.css"
import "@/src/app/styles/reset.css"
import "@/src/shared/ui/styles/vars.css"
import { Providers } from "@/src/app"
import { initServerSideMocks } from "@/src/shared/api/index.server"

initServerSideMocks()

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
}

export function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode
}>) {
   return (
      <html lang="en">
         <body>
            <Providers>{children}</Providers>
         </body>
      </html>
   )
}
