openapi: 3.0.0
info:
   title: API for Story Quests website
   version: 1.0.0
   description: API
paths:
   /stories:
      get:
         $ref: "./endpoints/stories.yaml#/findMany"

   /stories/{storyId}:
      get:
         $ref: "./endpoints/stories.yaml#/findOne"

   /stories/{storyId}/scenes:
      get:
         $ref: "./endpoints/stories.yaml#/findScenes"

   /stories/{storyId}/like:
      patch:
         $ref: "./endpoints/stories.yaml#/like"

   /auth/login:
      post:
         $ref: "./endpoints/auth.yaml#/login"

   /auth/session:
      get:
         $ref: "./endpoints/auth.yaml#/session"

components:
   schemas:
      Story:
      StoryLike:
         $ref: "./endpoints/stories.yaml#/components/schemas/StoryLike"
      Scene:
         $ref: "./endpoints/stories.yaml#/components/schemas/Scene"
      Answer:
         $ref: "./endpoints/stories.yaml#/components/schemas/Answer"
      User:
         $ref: "./endpoints/auth.yaml#/components/schemas/User"
      LoginRequest:
         $ref: "./endpoints/auth.yaml#/components/schemas/LoginRequest"
      Error:
         type: object
         required:
            - message
            - code
         properties:
            message:
               type: string
            code:
               type: string
   securitySchemas:
      cookieAuth:
      type: apiKey
      in: cookie
      name: token
