# api/schema/main.yaml
openapi: 3.0.0
info:
   title: API for Story Quests website
   version: 1.0.0
   description: API
paths:
   /stories:
      get:
         $ref: "./endpoints/stories.yaml#/findMany"

   /stories/{storyId}:
      get:
         $ref: "./endpoints/stories.yaml#/findOne"

   /scenes:
      get:
         $ref: "./endpoints/scenes.yaml#/findMany"

   /scenes/{sceneId}:
      get:
         $ref: "./endpoints/scenes.yaml#/findOne"

components:
   schemas:
      Story: # ... (уже определено ранее)
      Scene: # Ссылка на общую схему Scene
         $ref: "./endpoints/scenes.yaml#/components/schemas/Scene"
      Answer: # Ссылка на общую схему Answer
         $ref: "./endpoints/scenes.yaml#/components/schemas/Answer"
      Error: # ... (определение ошибки из responses.yaml)
         type: object
         required:
            - message
            - code
         properties:
            message:
               type: string
            code:
               type: string
